#Hyper Params
batch_size: 64
lr: 0.001
num_epochs: 10
n_workers: 0
model: tf_transformer
loader: base
log_step: 200

# Dataset
ds_name: electricity
train_samples: 450000
test_samples: 50000
val_samples: 50000
input_size: 5
output_size: 1
total_time_steps: 192
num_encoder_steps: 168
static_input_loc:
- 4
input_obs_loc:
- 0
known_categorical_inputs:
- 0
known_regular_inputs:
- 1
- 2
- 3
category_counts:
- 369

# Model Temporal Fusion Transformer
quantiles:
- 0.1
- 0.5
- 0.9
batch_first: true
early_stopping_patience: 5
hidden_layer_size: 160
stack_size: 1
dropout_rate: 0
max_gradient_norm: 0.01
learning_rate: 0.001
num_heads: 4
